{{- if not .Values.monitoring.resourcesOnly }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "platform-api.name" . }}
  labels:
    {{- include "platform-api.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
